src/Blogger/BlogBundle/Entity/Blog.php
<?php
// src/Blogger/BlogBundle/Entity/Blog.php

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Blogger\BlogBundle\HelpTools\HelpTools;

/**
 * @ORM\Entity(repositoryClass="Blogger\BlogBundle\Entity\Repository\BlogRepository")
 * @ORM\Table(name="blog")
 * @ORM\HasLifecycleCallbacks
 */
class Blog
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string")
     */
    protected $title;

    /**
     * @ORM\Column(type="string")
     */
    protected $slug;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $author;

    /**
     * @ORM\Column(type="text")
     */
    protected $blog;

    /**
     * @ORM\Column(type="string", length=20)
     */
    protected $image;

    /**
     *
     * @ORM\ManyToMany(targetEntity="Tag", inversedBy="blogs")
     * @ORM\JoinTable(name="blog_tags",
     *      joinColumns={@ORM\JoinColumn(name="blog_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="tag_id", referencedColumnName="id")}
     *      )
     */
    protected $tags;

    protected $tagString;

    /**
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="blogs")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id", onDelete="SET NULL")
     */
    protected $category;

    /**
     * @ORM\OneToMany(targetEntity="Comment", mappedBy="blog")
     */
    protected $comments;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $created;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $updated;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $posted;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Blog
     */
    public function setTitle($title)
    {
        $this->title = $title;

        $this->setSlug($this->title);

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set author
     *
     * @param string $author
     * @return Blog
     */
    public function setAuthor($author)
    {
        $this->author = $author;
    
        return $this;
    }

    /**
     * Get author
     *
     * @return string 
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Set blog
     *
     * @param string $blog
     * @return Blog
     */
    public function setBlog($blog)
    {
        $this->blog = $blog;
    
        return $this;
    }

    /**
     * Get blog
     *
     * @return string
     */
    public function getBlog($length = null)
    {
        if (false === is_null($length) && $length > 0)
            return substr($this->blog, 0, $length);
        else
            return $this->blog;
    }

    /**
     * Set image
     *
     * @param string $image
     * @return Blog
     */
    public function setImage($image)
    {
        $this->image = $image;
    
        return $this;
    }

    /**
     * Get image
     *
     * @return string 
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Blog
     */
    public function setCreated($created)
    {
        $this->created = $created;
    
        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     * @return Blog
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;
    
        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime 
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    public function addComment(Comment $comment)
    {
        $this->comments[] = $comment;
    }

    public function getComments()
    {
        return $this->comments;
    }

    public function __construct()
    {
        $this->comments = new ArrayCollection();

        $this->setCreated(new \DateTime());
        $this->setUpdated(new \DateTime());
        $this->setAuthor("Admin");
        $this->setPosted(false);
        $this->setImage("default.png");
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedValue()
    {
        $this->setUpdated(new \DateTime());
    }

    /**
     * Remove comments
     *
     * @param \Blogger\BlogBundle\Entity\Comment $comments
     */
    public function removeComment(\Blogger\BlogBundle\Entity\Comment $comments)
    {
        $this->comments->removeElement($comments);
    }

    public function __toString()
    {
        return $this->getTitle();
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Blog
     */
    public function setSlug($slug)
    {
        $this->slug = HelpTools::slugify($slug);
    
        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Add tags
     *
     * @param \Blogger\BlogBundle\Entity\Tag $tags
     * @return Blog
     */
    public function addTag(\Blogger\BlogBundle\Entity\Tag $tags)
    {
        $this->tags[] = $tags;
    
        return $this;
    }

    /**
     * Remove tags
     *
     * @param \Blogger\BlogBundle\Entity\Tag $tags
     */
    public function removeTag(\Blogger\BlogBundle\Entity\Tag $tag)
    {
        $this->tags->removeElement($tag);
    }

    /**
     * Set category
     *
     * @param \Blogger\BlogBundle\Entity\Category $category
     * @return Blog
     */
    public function setCategory(\Blogger\BlogBundle\Entity\Category $category = null)
    {
        $this->category = $category;
    
        return $this;
    }

    /**
     * Get category
     *
     * @return \Blogger\BlogBundle\Entity\Category 
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set posted
     *
     * @param boolean $posted
     * @return Blog
     */
    public function setPosted($posted)
    {
        $this->posted = $posted;
    
        return $this;
    }

    /**
     * Get posted
     *
     * @return boolean 
     */
    public function getPosted()
    {
        return $this->posted;
    }

    public function setTagString($tagString)
    {
        $this->tagString = $tagString;

        return $this;
    }

    public function getTagString()
    {
        return $this->tagString;
    }

    public function getTagsAsString()
    {
        $tags = $this->getTags();
        $tagNameArray = array();
        foreach($tags as $tag) {
            $tagNameArray[] = $tag->getName();
        }
        return implode(", ", $tagNameArray);
    }

    /**
     * Get blogs
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTags()
    {
        return $this->tags;
    }
}

src/Blogger/BlogBundle/Entity/Tag.php
<?php
namespace Blogger\BlogBundle\Entity;

use Blogger\BlogBundle\HelpTools\HelpTools;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="Blogger\BlogBundle\Entity\Repository\TagRepository")
 * @ORM\Table(name="tag")
 */
class Tag
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToMany(targetEntity="Post", mappedBy="tags")
     */
    protected $posts;

    /**
     * @ORM\Column(type="string")
     */
    protected $name;

    /**
     * @ORM\Column(type="string")
     */
    protected $slug;

    protected $weight;
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->weight = 0;
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Tag
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Tag
     */
    public function setSlug($slug)
    {
        $this->slug = HelpTools::slugify($slug);
    
        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set weight
     *
     * @param \int $weight
     * @return Tag
     */
    public function setWeight($weight)
    {
        $this->weight = $weight;
    
        return $this;
    }

    /**
     * Get weight
     *
     * @return \int 
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Add posts
     *
     * @param \Blogger\BlogBundle\Entity\Post $posts
     * @return Tag
     */
    public function addPost(\Blogger\BlogBundle\Entity\Post $posts)
    {
        $this->posts[] = $posts;
    
        return $this;
    }

    /**
     * Remove posts
     *
     * @param \Blogger\BlogBundle\Entity\Post $posts
     */
    public function removePost(\Blogger\BlogBundle\Entity\Post $posts)
    {
        $this->posts->removeElement($posts);
    }

    /**
     * Get posts
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getPosts()
    {
        return $this->posts;
    }

    public function getPostCount()
    {
        return $this->posts->count();
    }

    public function getPostedPostCount() {
        $postedPostCount = 0;
        foreach($this->posts as $post) {
            if($post->getPosted() == 1)
                $postedPostCount++;
        }
        return $postedPostCount;
    }

    public function __toString()
    {
        return $this->getName();
    }
}

src/Blogger/BlogBundle/Resources/views/Page/about.html.twig
{% extends 'BloggerBlogBundle::layout.html.twig' %}

{% block title %}About{% endblock%}

{% block body %}
    <header>
        <h1>About symfony-blog</h1>
    </header>
    <article>
        <p>Donec imperdiet ante sed diam consequat et dictum erat faucibus. Aliquam sit
        amet vehicula leo. Morbi urna dui, tempor ac posuere et, rutrum at dui.
        Curabitur neque quam, ultricies ut imperdiet id, ornare varius arcu. Ut congue
        urna sit amet tellus malesuada nec elementum risus molestie. Donec gravida
        tellus sed tortor adipiscing fringilla. Donec nulla mauris, mollis egestas
        condimentum laoreet, lacinia vel lorem. Morbi vitae justo sit amet felis
        vehicula commodo a placerat lacus. Mauris at est elit, nec vehicula urna. Duis a
        lacus nisl. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
        posuere cubilia Curae.</p>
    </article>
{% endblock %}

src/Blogger/BlogBundle/Resources/views/Page/category.html.twig
{# src/Blogger/BlogBundle/Resources/views/Page/index.html.twig #}
{% extends 'BloggerBlogBundle::layout.html.twig' %}

{% block body %}
    <h1>Blogs in category {{ cat.name }}</h1>
    {% for blog in blogs %}
        <article class="blog">
            <div class="date"><time datetime="{{ blog.created|date('c') }}">{{ blog.created|date('l, F j, Y') }}</time></div>
            <header>
                <h2><a href="{{ path('BloggerBlogBundle_blog_show', { 'id': blog.id, 'slug': blog.slug }) }}">{{ blog.title }}</a></h2>
            </header>

            <img src="{{ asset(['images/', blog.image]|join) }}" />
            <div class="snippet">
                <p>{{ blog.blog(500) }}</p>
                <p class="continue"><a href="{{ path('BloggerBlogBundle_blog_show', { 'id': blog.id, 'slug': blog.slug }) }}">Continue reading...</a></p>
            </div>

            <footer class="meta">
                <p>Comments: <a href="{{ path('BloggerBlogBundle_blog_show', { 'id': blog.id, 'slug': blog.slug }) }}#comments">{{ blog.comments|length }}</a></p>
                <p>Posted by <span class="highlight">{{ blog.author }}</span> at {{ blog.created|date('h:iA') }}</p>
                <p>Tags: <span class="highlight">{# {{ blog.tags }} #}</span></p>
            </footer>
        </article>
    {% else %}
        <p>There are no blog entries for symblog</p>
    {% endfor %}
{% endblock %}

src/Blogger/BlogBundle/Resources/views/Page/contact.html.twig
{% extends 'BloggerBlogBundle::layout.html.twig' %}{% block title %}Contact{% endblock%}{% block body %}    <header>        <h1>Contact symblog</h1>    </header>    {% for flashMessage in app.session.flashbag.get('blogger-notice') %}        <div class="blogger-notice">            {{ flashMessage  }}        </div>    {% endfor %}    <p>Want to contact symblog?</p>    <form action="{{ path('BloggerBlogBundle_contact') }}" method="post" {{ form_enctype(form) }} class="blogger">        {{ form_errors(form) }}        {{ form_row(form.name) }}        {{ form_row(form.email) }}        {{ form_row(form.subject) }}        {{ form_row(form.body) }}        {{ form_rest(form) }}        <input type="submit" value="Submit" />    </form>{% endblock %}

src/Blogger/BlogBundle/Resources/views/Page/contactEmail.txt.twig
{# src/Blogger/BlogBundle/Resources/views/Page/contactEmail.txt.twig #}
A contact enquiry was made by {{ enquiry.name }} at {{ "now" | date("Y-m-d H:i") }}.

Reply-To: {{ enquiry.email }}
Subject: {{ enquiry.subject }}
Body:
{{ enquiry.body }}

src/Blogger/BlogBundle/Resources/views/Page/index.html.twig
{# src/Blogger/BlogBundle/Resources/views/Page/index.html.twig #}{% extends 'BloggerBlogBundle::layout.html.twig' %}{% block body %}    {% for post in pagination %}        <article class="post">            <div class="date"><time datetime="{{ post.created|date('c') }}">{{ post.created|date('l, F j, Y') }}</time></div>            <header>                <h2><a href="{{ path('BloggerBlogBundle_post_show', { 'id': post.id, 'slug': post.slug }) }}">{{ post.title }}</a></h2>            </header>            <img src="{{ asset(['images/', post.image]|join) }}" />            <div class="snippet">                <p>{{ post.post(500) | raw }}</p>                <p class="continue"><a href="{{ path('BloggerBlogBundle_post_show', { 'id': post.id, 'slug': post.slug }) }}">Continue reading...</a></p>            </div>            <footer class="meta">                <p>Comments: <a href="{{ path('BloggerBlogBundle_post_show', { 'id': post.id, 'slug': post.slug }) }}#comments">{{ post.comments|length }}</a></p>                <p>Posted by <span class="highlight">{{ post.author.username }}</span> at {{ post.created|date('h:iA') }}</p>                <p>Category: <span class="highlight">{{ post.category }} </span></p>                <p>Tags: <span class="highlight">{{ post.tagsAsString }} </span></p>            </footer>        </article>    {% else %}        <p>There are no post entries for symfony-blog</p>    {% endfor %}    <div class="navigation">        {{ knp_pagination_render(pagination) }}    </div>{% endblock %}

src/Blogger/BlogBundle/Resources/views/Page/sidebar.html.twig
{# src/Blogger/BlogBundle/Resources/views/Page/sidebar.html.twig #}
<section class="section">
    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
        <header>
            <h3>User menu</h3>
        </header>
        <p>Hello {{ app.user.username }}</p>
        <ul class="categories">
            <li><a href="{{ path('BloggerAdminBundle_homepage') }}">Go to admin panel</a></li>
            <li><a href="{{ path('logout') }}">Log out</a></li>
        </ul>
    {% else %}
        <header>
            <h3>Authorization</h3>
        </header>
        <ul class="categories">
            <li><a href="{{ path('login') }}">Log in</a></li>
            <li><a href="{{ path('register') }}">Sign in</a></li>
        </ul>
    {% endif %}
</section>
<section class="section">
    <header>
        <h3>Categories</h3>
    </header>
    <ul class="categories">
        {% for category in categories %}
        <li style="padding-left: {{ category['offset']*20 }}px"><a href="{{ path('BloggerBlogBundle_category', { 'slug': category['category'].slug }) }}">{{ category['category'].name }}</a> ({{ category['category'].postCount }})</li>
        {% endfor %}
    </ul>
</section>
<section class="section">
    <header>
        <h3>Tag Cloud</h3>
    </header>
    <p class="tags">
        {% for tag in tags %}
        <a href="{{ path('BloggerBlogBundle_tag', { 'slug': tag.slug }) }}" style="font-size:{{ tag.weight }}px" title="{{ tag.postedpostCount }}">{{ tag }}</a>
        {% else %}
        <p>There are no tags</p>
        {% endfor %}
    </p>
</section>
<section class="section">
    <header>
        <h3>Latest Comments</h3>
    </header>
    {% for comment in latestComments %}
        <article class="comment">
            <header>
                <p class="small"><span class="highlight">{{ comment.user }}</span> commented on
                    <a href="{{ path('BloggerBlogBundle_post_show', { 'id': comment.post.id , 'slug': comment.post.slug }) }}#comment-{{ comment.id }}">
                        {{ comment.post.title }}
                    </a>
                    [<em><time datetime="{{ comment.created|date('c') }}">{{ comment.created|created_ago }}</time></em>]
                </p>
            </header>
            <p>{{ comment.comment }}</p>
        </article>
    {% else %}
        <p>There are no recent comments</p>
    {% endfor %}
</section>

src/Blogger/BlogBundle/Resources/views/Page/tag.html.twig
{# src/Blogger/BlogBundle/Resources/views/Page/tag.html.twig #}
{% extends 'BloggerBlogBundle::Page/index.html.twig' %}

{% block body %}
    <h1>Postss on tag "{{ tag.name }}"</h1>
    {{ parent(pagination) }}
{% endblock %}